// Generated by https://quicktype.io

import { EditableTable } from './TableColumn';

export interface ICampaign extends EditableTable {
  id: number;
  CampaignId: string;
  Title: string;
  Description: string;
  CampaignType: string;
  CampaignValue: string;
  ButtonText: string;
  IsActive: boolean;
  StartDate: string;
  EndDate: string;
  CreatedBy: string;
  UpdatedBy: string;
  CreatedAt: string;
  UpdatedAt: string;
}
