// Generated by https://quicktype.io

import { EditableTable } from './TableColumn';

// Generated by https://quicktype.io

export interface ICampaign extends EditableTable{
  id:             number;
  CampaignId:     string;
  Title:          string;
  Description:    string;
  Footer:         string;
  StartDate:      string;
  EndDate:        string;
  BoosterValue:   number;
  ButtonText:     string;
  InstantBooster: boolean;
  IsActive:       boolean;
  CreatedBy:      string;
  UpdatedBy:      string;
  CreatedAt:      string;
  UpdatedAt:      string;
}
