// Generated by https://quicktype.io

import { locationUploadRes } from "./commondisplay";

export interface IEvents {
  id:                number;
  EventId:           string;
  Title:             string;
  Description:       string;
  Points:            number;
  IsActive:          boolean;
  TermsAndCondition: string;
  DirectoryId:       string;
  ThumbNail:         string;
  AdStartDate:       string;
  AdEndDate:         string;
  AdFile:            string;
  CreatedBy:         string;
  UpdatedBy:         string;
  CreatedAt:         string;
  UpdatedAt:         string;
  peakHours:         PeakHour[];
  location:          locationUploadRes[];
}
export interface PeakHour {
  id?:        number;
  mapId?:     number;
  Points:    number;
  Date:      string;
  StartHour: string;
  EndHour:   string;
  CreatedBy?: string;
  UpdatedBy?: string;
  CreatedAt?: string;
  UpdatedAt?: string;
}
