// Generated by https://quicktype.io

import { EditableTable } from './TableColumn';

export interface IEventAnalytics {
  report: EventReport[];
  analytics: EventAnalytics;
}

export interface EventAnalytics {
  TotalViews: string;
}

export interface EventReport extends EditableTable {
  id: number;
  PublicUserId: number;
  UserName: string;
  Gender: string;
  DOB?: string;
  PinCode: string;
  Occupation?: null;
  PhoneNumber: string;
  CompletedScreen: string;
  CompletedScreenId: number;
  CompletedPercentage: string;
  createdAt: string;
  updatedAt: string;
  lastLogin: string;
  EventId: number;
  DistributedDate: string;
  RedeemDate: string;
  Remarks: string;
  IsPriceDistributed: boolean;
  totalpoints: string;
  isWinner: boolean;
  rank:number;
}

export enum CompletedScreen {
  Pincode = 'pincode',
}

export enum Gender {
  Female = 'female',
  Male = 'male',
}
