name: Deploy to Server

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'qa'
        type: choice
        options:
        - prod
        - qa
      branchname:
        description: 'Branch Name'
        required: true


jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Branch Name: ${{ github.event.inputs.branchname }}"
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branchname }}
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.15.1
    - uses: haya14busa/action-cond@v1
      id: environment
      with:
        cond: ${{ github.event.inputs.environment == 'prod' }}
        if_true: "npm run build"
        if_false: "npm run build-test"
    - name: Install dependencies
      run: npm i
    - name: Build
      run: ${{ steps.environment.outputs.value }}
    - uses: haya14busa/action-cond@v1
      id: dirname
      with:
        cond: ${{ github.event.inputs.environment == 'prod' }}
        if_true: "app"
        if_false: "dtboxqa"
    - name: Create Build tar
      run: |
        mkdir ${{ steps.dirname.outputs.value }}
        #cp -TR . ${{ steps.dirname.outputs.value }}
        cp -TR ./dist/Dento ${{ steps.dirname.outputs.value }}
        cp .htaccess ./${{ steps.dirname.outputs.value }}
    - name: Copy Code to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVERHOST }}
        username: ${{ secrets.SERVERUSERNAME }}
        password: ${{ secrets.SERVERPASSWORD }}
        port: ${{ secrets.SERVERSSHPORT }}
        source: ${{ steps.dirname.outputs.value }}
        rm: true
        target: "/var/www/html/${{ steps.dirname.outputs.value }}"
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVERHOST }}
        username: ${{ secrets.SERVERUSERNAME }}
        password: ${{ secrets.SERVERPASSWORD }}
        port: ${{ secrets.SERVERSSHPORT }}
        script: |
              cd /var/www/html/${{ steps.dirname.outputs.value }}
              mkdir /var/www/html/temp
              mv -f ${{ steps.dirname.outputs.value }} /var/www/html/temp
              rm -r /var/www/html/${{ steps.dirname.outputs.value }}
              mv -f /var/www/html/temp/${{ steps.dirname.outputs.value }} /var/www/html/
              rm -r /var/www/html/temp
